{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UploaderService",
   "type": "table",
   "description": "the uploader service logging",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app_kubernetes_io_component=\"upload-service\"} |= ``",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "BackendAPI",
   "type": "table",
   "description": "the uploader service logging",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app_kubernetes_io_component=\"backend-api\"} |= ``",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Pusher",
   "type": "table",
   "description": "the uploader service logging",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app_kubernetes_io_component=\"image-processor\"} |= ``",
     "maxLines": 100
    }
   ]
  }
 ]
}